## kn-admin

`kn admin` helps for Knative configuration when running on a Kubernetes cluster.

### Description

This kn-admin plugin is designed to help administrators and operators better manage a Knative platform installation with kn CLI.
The plugin’s main objective is to make administration and operation workflows easier, for instance by making it easy to accomplish
tasks such as feature flags enablement or disablement with one command, instead of many manual steps like modifying ConfigMaps or yaml files.

### Usage

----
A plugin of kn client to manage Knative for administrators.

For example:
kn admin domain set - to set Knative route domain
kn admin private-registry enable - to enable deployment from the private registry
kn admin autoscaling update - to manage autoscaling config

Usage:
  kn admin [command]

Available Commands:
  autoscaling Manage autoscaling config
  domain      Manage route domain
  help        Help about any command
  registry    Manage registry
  version     Prints the plugin version

Flags:
      --config string   config file (default is $HOME/.config/kn/plugins/admin.yaml)
  -h, --help            help for kn admin
  -t, --toggle          Help message for toggle

Use "kn admin [command] --help" for more information about a command.
----

#### `kn admin domain`

----
Set default route domain or route domain for Service with selectors. For example:

kn admin domain set - to set Knative route domain

Usage:
  kn admin domain [flags]
  kn admin domain [command]

Available Commands:
  set         set route domain
  unset       unset route domain

Flags:
  -h, --help   help for domain

Global Flags:
      --config string   config file (default is $HOME/.config/kn/plugins/admin.yaml)

Use "admin domain [command] --help" for more information about a command.

----

#### `kn admin registry`

----
Manage Service deployment from a private registry

For example:

kn admin registry add \
  --secret=[SECRET_NAME]
  --server=[REGISTRY_SERVER_URL] \
  --email=[REGISTRY_EMAIL] \
  --username=[REGISTRY_USER] \
  --password=[REGISTRY_PASSWORD]

Usage:
  kn admin registry [command]

Available Commands:
  add         Add registry with credentials
  help        Help about any command
  remove      Remove registry settings

Flags:
  -h, --help                    help for registry
  -n, --namespace string        the namespace to manage registries
  -s, --serviceaccount string   the serviceaccount to save imagePullSecrets

Global Flags:
      --config string   config file (default is $HOME/.config/kn/plugins/admin.yaml)

Use "kn admin registry [command] --help" for more information about a command.
----

#### `kn admin autoscaling`

----
Manage autoscaling provided by Knative Pod Autoscaler (KPA). For example:

kn admin autoscaling update - to manage autoscaling config

Usage:
  kn admin autoscaling [command]

Available Commands:
  update      update autoscaling config

Flags:
  -h, --help   help for autoscaling

Global Flags:
      --config string   config file (default is $HOME/.config/kn/plugins/admin.yaml)

Use "kn admin autoscaling [command] --help" for more information about a command.

----
### Examples

#### As a Knative administrator, I want to update Knative route domain with my custom domain.


.Update the default route domain if --selector no specified
====
----
$ kn admin domain set --custom-domain mydomain.com
Set Knative route domain mydomain.com
----
====

.Update a custom domain with --selector and Service with a label app=v1 will use test.com
====
----
$ kn admin domain set --custom-domain test.com --selector app=v1
Set Knative route domain test.com with selector [app=v1]
----
====

.Unset a route domain
====
----
$ kn-admin domain unset --custom-domain mydomain.com
Unset Knative route domain mydomain.com
----
====

#### As a Knative administrator, I want to enable deploying from private registry.

.Enable a private registry with given credentials for Service creation.
=====
-----
$ kn admin registry add \
  --secret=[SECRET_NAME] \
  --server=[REGISTRY_SERVER_URL] \
  --email=[REGISTRY_EMAIL] \
  --username=[REGISTRY_USER] \
  --password=[REGISTRY_PASSWORD] \
  --namespace=[NAMESPACE] \
  --serviceaccount=[SERVICE_ACCOUNT]
-----
=====

.Remove a private registry by server and username.
=====
-----
$ kn admin registry remove \
  --username=[REGISTRY_USER] \
  --server=[REGISTRY_SERVER_URL] \
  --namespace=[NAMESPACE] \
  --serviceaccount=[SERVICE_ACCOUNT]
-----
=====

#### As a Knative administrator, I want to enable scale-to-zero for autoscaling.

.Enable scale-to-zero for autoscaling.
=====
-----
$ kn admin autoscaling update --scale-to-zero
Updated Knative autoscaling config enable-scale-to-zero: true
-----
=====
