// Code generated by counterfeiter. DO NOT EDIT.
package typesfakes

import (
	"sync"

	"github.com/maximilien/kn-source-github/pkg/types"
	typesa "github.com/maximilien/kn-source-pkg/pkg/types"
	"github.com/spf13/pflag"
)

type FakeGHFlagsFactory struct {
	CreateFlagsStub        func() *pflag.FlagSet
	createFlagsMutex       sync.RWMutex
	createFlagsArgsForCall []struct {
	}
	createFlagsReturns struct {
		result1 *pflag.FlagSet
	}
	createFlagsReturnsOnCall map[int]struct {
		result1 *pflag.FlagSet
	}
	DeleteFlagsStub        func() *pflag.FlagSet
	deleteFlagsMutex       sync.RWMutex
	deleteFlagsArgsForCall []struct {
	}
	deleteFlagsReturns struct {
		result1 *pflag.FlagSet
	}
	deleteFlagsReturnsOnCall map[int]struct {
		result1 *pflag.FlagSet
	}
	DescribeFlagsStub        func() *pflag.FlagSet
	describeFlagsMutex       sync.RWMutex
	describeFlagsArgsForCall []struct {
	}
	describeFlagsReturns struct {
		result1 *pflag.FlagSet
	}
	describeFlagsReturnsOnCall map[int]struct {
		result1 *pflag.FlagSet
	}
	GHSourceFactoryStub        func() types.GHSourceFactory
	gHSourceFactoryMutex       sync.RWMutex
	gHSourceFactoryArgsForCall []struct {
	}
	gHSourceFactoryReturns struct {
		result1 types.GHSourceFactory
	}
	gHSourceFactoryReturnsOnCall map[int]struct {
		result1 types.GHSourceFactory
	}
	KnSourceFactoryStub        func() typesa.KnSourceFactory
	knSourceFactoryMutex       sync.RWMutex
	knSourceFactoryArgsForCall []struct {
	}
	knSourceFactoryReturns struct {
		result1 typesa.KnSourceFactory
	}
	knSourceFactoryReturnsOnCall map[int]struct {
		result1 typesa.KnSourceFactory
	}
	UpdateFlagsStub        func() *pflag.FlagSet
	updateFlagsMutex       sync.RWMutex
	updateFlagsArgsForCall []struct {
	}
	updateFlagsReturns struct {
		result1 *pflag.FlagSet
	}
	updateFlagsReturnsOnCall map[int]struct {
		result1 *pflag.FlagSet
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGHFlagsFactory) CreateFlags() *pflag.FlagSet {
	fake.createFlagsMutex.Lock()
	ret, specificReturn := fake.createFlagsReturnsOnCall[len(fake.createFlagsArgsForCall)]
	fake.createFlagsArgsForCall = append(fake.createFlagsArgsForCall, struct {
	}{})
	fake.recordInvocation("CreateFlags", []interface{}{})
	fake.createFlagsMutex.Unlock()
	if fake.CreateFlagsStub != nil {
		return fake.CreateFlagsStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.createFlagsReturns
	return fakeReturns.result1
}

func (fake *FakeGHFlagsFactory) CreateFlagsCallCount() int {
	fake.createFlagsMutex.RLock()
	defer fake.createFlagsMutex.RUnlock()
	return len(fake.createFlagsArgsForCall)
}

func (fake *FakeGHFlagsFactory) CreateFlagsCalls(stub func() *pflag.FlagSet) {
	fake.createFlagsMutex.Lock()
	defer fake.createFlagsMutex.Unlock()
	fake.CreateFlagsStub = stub
}

func (fake *FakeGHFlagsFactory) CreateFlagsReturns(result1 *pflag.FlagSet) {
	fake.createFlagsMutex.Lock()
	defer fake.createFlagsMutex.Unlock()
	fake.CreateFlagsStub = nil
	fake.createFlagsReturns = struct {
		result1 *pflag.FlagSet
	}{result1}
}

func (fake *FakeGHFlagsFactory) CreateFlagsReturnsOnCall(i int, result1 *pflag.FlagSet) {
	fake.createFlagsMutex.Lock()
	defer fake.createFlagsMutex.Unlock()
	fake.CreateFlagsStub = nil
	if fake.createFlagsReturnsOnCall == nil {
		fake.createFlagsReturnsOnCall = make(map[int]struct {
			result1 *pflag.FlagSet
		})
	}
	fake.createFlagsReturnsOnCall[i] = struct {
		result1 *pflag.FlagSet
	}{result1}
}

func (fake *FakeGHFlagsFactory) DeleteFlags() *pflag.FlagSet {
	fake.deleteFlagsMutex.Lock()
	ret, specificReturn := fake.deleteFlagsReturnsOnCall[len(fake.deleteFlagsArgsForCall)]
	fake.deleteFlagsArgsForCall = append(fake.deleteFlagsArgsForCall, struct {
	}{})
	fake.recordInvocation("DeleteFlags", []interface{}{})
	fake.deleteFlagsMutex.Unlock()
	if fake.DeleteFlagsStub != nil {
		return fake.DeleteFlagsStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.deleteFlagsReturns
	return fakeReturns.result1
}

func (fake *FakeGHFlagsFactory) DeleteFlagsCallCount() int {
	fake.deleteFlagsMutex.RLock()
	defer fake.deleteFlagsMutex.RUnlock()
	return len(fake.deleteFlagsArgsForCall)
}

func (fake *FakeGHFlagsFactory) DeleteFlagsCalls(stub func() *pflag.FlagSet) {
	fake.deleteFlagsMutex.Lock()
	defer fake.deleteFlagsMutex.Unlock()
	fake.DeleteFlagsStub = stub
}

func (fake *FakeGHFlagsFactory) DeleteFlagsReturns(result1 *pflag.FlagSet) {
	fake.deleteFlagsMutex.Lock()
	defer fake.deleteFlagsMutex.Unlock()
	fake.DeleteFlagsStub = nil
	fake.deleteFlagsReturns = struct {
		result1 *pflag.FlagSet
	}{result1}
}

func (fake *FakeGHFlagsFactory) DeleteFlagsReturnsOnCall(i int, result1 *pflag.FlagSet) {
	fake.deleteFlagsMutex.Lock()
	defer fake.deleteFlagsMutex.Unlock()
	fake.DeleteFlagsStub = nil
	if fake.deleteFlagsReturnsOnCall == nil {
		fake.deleteFlagsReturnsOnCall = make(map[int]struct {
			result1 *pflag.FlagSet
		})
	}
	fake.deleteFlagsReturnsOnCall[i] = struct {
		result1 *pflag.FlagSet
	}{result1}
}

func (fake *FakeGHFlagsFactory) DescribeFlags() *pflag.FlagSet {
	fake.describeFlagsMutex.Lock()
	ret, specificReturn := fake.describeFlagsReturnsOnCall[len(fake.describeFlagsArgsForCall)]
	fake.describeFlagsArgsForCall = append(fake.describeFlagsArgsForCall, struct {
	}{})
	fake.recordInvocation("DescribeFlags", []interface{}{})
	fake.describeFlagsMutex.Unlock()
	if fake.DescribeFlagsStub != nil {
		return fake.DescribeFlagsStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.describeFlagsReturns
	return fakeReturns.result1
}

func (fake *FakeGHFlagsFactory) DescribeFlagsCallCount() int {
	fake.describeFlagsMutex.RLock()
	defer fake.describeFlagsMutex.RUnlock()
	return len(fake.describeFlagsArgsForCall)
}

func (fake *FakeGHFlagsFactory) DescribeFlagsCalls(stub func() *pflag.FlagSet) {
	fake.describeFlagsMutex.Lock()
	defer fake.describeFlagsMutex.Unlock()
	fake.DescribeFlagsStub = stub
}

func (fake *FakeGHFlagsFactory) DescribeFlagsReturns(result1 *pflag.FlagSet) {
	fake.describeFlagsMutex.Lock()
	defer fake.describeFlagsMutex.Unlock()
	fake.DescribeFlagsStub = nil
	fake.describeFlagsReturns = struct {
		result1 *pflag.FlagSet
	}{result1}
}

func (fake *FakeGHFlagsFactory) DescribeFlagsReturnsOnCall(i int, result1 *pflag.FlagSet) {
	fake.describeFlagsMutex.Lock()
	defer fake.describeFlagsMutex.Unlock()
	fake.DescribeFlagsStub = nil
	if fake.describeFlagsReturnsOnCall == nil {
		fake.describeFlagsReturnsOnCall = make(map[int]struct {
			result1 *pflag.FlagSet
		})
	}
	fake.describeFlagsReturnsOnCall[i] = struct {
		result1 *pflag.FlagSet
	}{result1}
}

func (fake *FakeGHFlagsFactory) GHSourceFactory() types.GHSourceFactory {
	fake.gHSourceFactoryMutex.Lock()
	ret, specificReturn := fake.gHSourceFactoryReturnsOnCall[len(fake.gHSourceFactoryArgsForCall)]
	fake.gHSourceFactoryArgsForCall = append(fake.gHSourceFactoryArgsForCall, struct {
	}{})
	fake.recordInvocation("GHSourceFactory", []interface{}{})
	fake.gHSourceFactoryMutex.Unlock()
	if fake.GHSourceFactoryStub != nil {
		return fake.GHSourceFactoryStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.gHSourceFactoryReturns
	return fakeReturns.result1
}

func (fake *FakeGHFlagsFactory) GHSourceFactoryCallCount() int {
	fake.gHSourceFactoryMutex.RLock()
	defer fake.gHSourceFactoryMutex.RUnlock()
	return len(fake.gHSourceFactoryArgsForCall)
}

func (fake *FakeGHFlagsFactory) GHSourceFactoryCalls(stub func() types.GHSourceFactory) {
	fake.gHSourceFactoryMutex.Lock()
	defer fake.gHSourceFactoryMutex.Unlock()
	fake.GHSourceFactoryStub = stub
}

func (fake *FakeGHFlagsFactory) GHSourceFactoryReturns(result1 types.GHSourceFactory) {
	fake.gHSourceFactoryMutex.Lock()
	defer fake.gHSourceFactoryMutex.Unlock()
	fake.GHSourceFactoryStub = nil
	fake.gHSourceFactoryReturns = struct {
		result1 types.GHSourceFactory
	}{result1}
}

func (fake *FakeGHFlagsFactory) GHSourceFactoryReturnsOnCall(i int, result1 types.GHSourceFactory) {
	fake.gHSourceFactoryMutex.Lock()
	defer fake.gHSourceFactoryMutex.Unlock()
	fake.GHSourceFactoryStub = nil
	if fake.gHSourceFactoryReturnsOnCall == nil {
		fake.gHSourceFactoryReturnsOnCall = make(map[int]struct {
			result1 types.GHSourceFactory
		})
	}
	fake.gHSourceFactoryReturnsOnCall[i] = struct {
		result1 types.GHSourceFactory
	}{result1}
}

func (fake *FakeGHFlagsFactory) KnSourceFactory() typesa.KnSourceFactory {
	fake.knSourceFactoryMutex.Lock()
	ret, specificReturn := fake.knSourceFactoryReturnsOnCall[len(fake.knSourceFactoryArgsForCall)]
	fake.knSourceFactoryArgsForCall = append(fake.knSourceFactoryArgsForCall, struct {
	}{})
	fake.recordInvocation("KnSourceFactory", []interface{}{})
	fake.knSourceFactoryMutex.Unlock()
	if fake.KnSourceFactoryStub != nil {
		return fake.KnSourceFactoryStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.knSourceFactoryReturns
	return fakeReturns.result1
}

func (fake *FakeGHFlagsFactory) KnSourceFactoryCallCount() int {
	fake.knSourceFactoryMutex.RLock()
	defer fake.knSourceFactoryMutex.RUnlock()
	return len(fake.knSourceFactoryArgsForCall)
}

func (fake *FakeGHFlagsFactory) KnSourceFactoryCalls(stub func() typesa.KnSourceFactory) {
	fake.knSourceFactoryMutex.Lock()
	defer fake.knSourceFactoryMutex.Unlock()
	fake.KnSourceFactoryStub = stub
}

func (fake *FakeGHFlagsFactory) KnSourceFactoryReturns(result1 typesa.KnSourceFactory) {
	fake.knSourceFactoryMutex.Lock()
	defer fake.knSourceFactoryMutex.Unlock()
	fake.KnSourceFactoryStub = nil
	fake.knSourceFactoryReturns = struct {
		result1 typesa.KnSourceFactory
	}{result1}
}

func (fake *FakeGHFlagsFactory) KnSourceFactoryReturnsOnCall(i int, result1 typesa.KnSourceFactory) {
	fake.knSourceFactoryMutex.Lock()
	defer fake.knSourceFactoryMutex.Unlock()
	fake.KnSourceFactoryStub = nil
	if fake.knSourceFactoryReturnsOnCall == nil {
		fake.knSourceFactoryReturnsOnCall = make(map[int]struct {
			result1 typesa.KnSourceFactory
		})
	}
	fake.knSourceFactoryReturnsOnCall[i] = struct {
		result1 typesa.KnSourceFactory
	}{result1}
}

func (fake *FakeGHFlagsFactory) UpdateFlags() *pflag.FlagSet {
	fake.updateFlagsMutex.Lock()
	ret, specificReturn := fake.updateFlagsReturnsOnCall[len(fake.updateFlagsArgsForCall)]
	fake.updateFlagsArgsForCall = append(fake.updateFlagsArgsForCall, struct {
	}{})
	fake.recordInvocation("UpdateFlags", []interface{}{})
	fake.updateFlagsMutex.Unlock()
	if fake.UpdateFlagsStub != nil {
		return fake.UpdateFlagsStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.updateFlagsReturns
	return fakeReturns.result1
}

func (fake *FakeGHFlagsFactory) UpdateFlagsCallCount() int {
	fake.updateFlagsMutex.RLock()
	defer fake.updateFlagsMutex.RUnlock()
	return len(fake.updateFlagsArgsForCall)
}

func (fake *FakeGHFlagsFactory) UpdateFlagsCalls(stub func() *pflag.FlagSet) {
	fake.updateFlagsMutex.Lock()
	defer fake.updateFlagsMutex.Unlock()
	fake.UpdateFlagsStub = stub
}

func (fake *FakeGHFlagsFactory) UpdateFlagsReturns(result1 *pflag.FlagSet) {
	fake.updateFlagsMutex.Lock()
	defer fake.updateFlagsMutex.Unlock()
	fake.UpdateFlagsStub = nil
	fake.updateFlagsReturns = struct {
		result1 *pflag.FlagSet
	}{result1}
}

func (fake *FakeGHFlagsFactory) UpdateFlagsReturnsOnCall(i int, result1 *pflag.FlagSet) {
	fake.updateFlagsMutex.Lock()
	defer fake.updateFlagsMutex.Unlock()
	fake.UpdateFlagsStub = nil
	if fake.updateFlagsReturnsOnCall == nil {
		fake.updateFlagsReturnsOnCall = make(map[int]struct {
			result1 *pflag.FlagSet
		})
	}
	fake.updateFlagsReturnsOnCall[i] = struct {
		result1 *pflag.FlagSet
	}{result1}
}

func (fake *FakeGHFlagsFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createFlagsMutex.RLock()
	defer fake.createFlagsMutex.RUnlock()
	fake.deleteFlagsMutex.RLock()
	defer fake.deleteFlagsMutex.RUnlock()
	fake.describeFlagsMutex.RLock()
	defer fake.describeFlagsMutex.RUnlock()
	fake.gHSourceFactoryMutex.RLock()
	defer fake.gHSourceFactoryMutex.RUnlock()
	fake.knSourceFactoryMutex.RLock()
	defer fake.knSourceFactoryMutex.RUnlock()
	fake.updateFlagsMutex.RLock()
	defer fake.updateFlagsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGHFlagsFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ types.GHFlagsFactory = new(FakeGHFlagsFactory)
