// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"knative.dev/eventing-contrib/github/pkg/client/clientset/versioned/typed/sources/v1alpha1"
)

type FakeGitHubSourcesGetter struct {
	GitHubSourcesStub        func(string) v1alpha1.GitHubSourceInterface
	gitHubSourcesMutex       sync.RWMutex
	gitHubSourcesArgsForCall []struct {
		arg1 string
	}
	gitHubSourcesReturns struct {
		result1 v1alpha1.GitHubSourceInterface
	}
	gitHubSourcesReturnsOnCall map[int]struct {
		result1 v1alpha1.GitHubSourceInterface
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGitHubSourcesGetter) GitHubSources(arg1 string) v1alpha1.GitHubSourceInterface {
	fake.gitHubSourcesMutex.Lock()
	ret, specificReturn := fake.gitHubSourcesReturnsOnCall[len(fake.gitHubSourcesArgsForCall)]
	fake.gitHubSourcesArgsForCall = append(fake.gitHubSourcesArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GitHubSources", []interface{}{arg1})
	fake.gitHubSourcesMutex.Unlock()
	if fake.GitHubSourcesStub != nil {
		return fake.GitHubSourcesStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.gitHubSourcesReturns
	return fakeReturns.result1
}

func (fake *FakeGitHubSourcesGetter) GitHubSourcesCallCount() int {
	fake.gitHubSourcesMutex.RLock()
	defer fake.gitHubSourcesMutex.RUnlock()
	return len(fake.gitHubSourcesArgsForCall)
}

func (fake *FakeGitHubSourcesGetter) GitHubSourcesCalls(stub func(string) v1alpha1.GitHubSourceInterface) {
	fake.gitHubSourcesMutex.Lock()
	defer fake.gitHubSourcesMutex.Unlock()
	fake.GitHubSourcesStub = stub
}

func (fake *FakeGitHubSourcesGetter) GitHubSourcesArgsForCall(i int) string {
	fake.gitHubSourcesMutex.RLock()
	defer fake.gitHubSourcesMutex.RUnlock()
	argsForCall := fake.gitHubSourcesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeGitHubSourcesGetter) GitHubSourcesReturns(result1 v1alpha1.GitHubSourceInterface) {
	fake.gitHubSourcesMutex.Lock()
	defer fake.gitHubSourcesMutex.Unlock()
	fake.GitHubSourcesStub = nil
	fake.gitHubSourcesReturns = struct {
		result1 v1alpha1.GitHubSourceInterface
	}{result1}
}

func (fake *FakeGitHubSourcesGetter) GitHubSourcesReturnsOnCall(i int, result1 v1alpha1.GitHubSourceInterface) {
	fake.gitHubSourcesMutex.Lock()
	defer fake.gitHubSourcesMutex.Unlock()
	fake.GitHubSourcesStub = nil
	if fake.gitHubSourcesReturnsOnCall == nil {
		fake.gitHubSourcesReturnsOnCall = make(map[int]struct {
			result1 v1alpha1.GitHubSourceInterface
		})
	}
	fake.gitHubSourcesReturnsOnCall[i] = struct {
		result1 v1alpha1.GitHubSourceInterface
	}{result1}
}

func (fake *FakeGitHubSourcesGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.gitHubSourcesMutex.RLock()
	defer fake.gitHubSourcesMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGitHubSourcesGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ v1alpha1.GitHubSourcesGetter = new(FakeGitHubSourcesGetter)
